pts = np.concatenate([df.pt3,df.pt2,df.pt1,df.pt0])
w = np.concatenate([df.weight,df.weight,df.weight,df.weight])
b = np.linspace(30,120,60)
#b = np.linspace(0,1000,100)
sig = np.concatenate([df['s_or_b_4']>0.5,df['s_or_b_4']>0.5,df['s_or_b_4']>0.5,df['s_or_b_4']>0.5])
back = np.concatenate([df['s_or_b_4']<0.5,df['s_or_b_4']<0.5,df['s_or_b_4']<0.5,df['s_or_b_4']<0.5])
plt.hist(pts[sig], bins=b, histtype='step', label="single-vertex", weights=w[sig], color='tab:blue')
plt.hist(pts[back], bins=b, histtype='step', label="multi-vertex", weights=w[back], color = 'tab:orange')
plt.hist(pts, bins=b, histtype='step', label="Inclusive", weights=w, color='black')
plt.xlabel('4th leading jet pT [GeV]')
plt.ylabel('Weighted entries [A.U.]')
plt.yscale('log')
plt.grid()
plt.legend()
plt.show()

